フォームから値を挿入
kenta-yamazaki/Bento pull request #11
Opened 2019-07-22 02:08 UTC by reika-takamiya

#6 を作成しました。
レビューお願いします。

2019-07-23 01:27 UTC, shunji-yamaguchi requested changes
@reika-takamiya 
レビューしました。ご確認をよろしくお願いします。

（gradle wrapper のおかげでアプリ動かせました。ありがとうございます。）

2019-07-23 01:27 UTC, shunji-yamaguchi commented on src/main/java/jp/co/esm/bento/application/controller/BentoController.java
> +//@NoArgsConstructor
@reika-takamiya 
不要なコメントであればなるべく削除しておいてください。

2019-07-23 01:27 UTC, shunji-yamaguchi commented on src/main/java/jp/co/esm/bento/application/controller/BentoController.java
>          return bentoService.selectAll();
@reika-takamiya 
`@Controller` であれば返り値は遷移先のViewを指定するのが基本です。
これだとエラーになると思うので、不要であれば削除するか `@RestController` のコントローラークラスを別に作るのが良いです。
`@Controller` と `@RestController` の違いは以下が参考になりました。
https://qiita.com/tag1216/items/3680b92cf96eb5a170f0

2019-07-23 01:27 UTC, shunji-yamaguchi commented on src/main/java/jp/co/esm/bento/application/controller/BentoController.java
>          return result;
@reika-takamiya
こちらも `@Controller` だと動作しなさそうです。

2019-07-23 01:27 UTC, shunji-yamaguchi commented on src/main/java/jp/co/esm/bento/application/controller/BentoController.java
> +        return "order";
@reika-takamiya 
遷移先のView（HTML）がないようです。コミットしておいてください。

2019-07-23 01:27 UTC, shunji-yamaguchi commented on src/main/java/jp/co/esm/bento/application/controller/BentoController.java
> +            return "orderHistory";
@reika-takamiya 
遷移先のView（HTML）がないようです。コミットしておいてください。

2019-07-23 01:27 UTC, shunji-yamaguchi commented on src/main/java/jp/co/esm/bento/application/service/BentoService.java
> +    private BentoRepository bentoRepository;
@reika-takamiya 
フィールドインジェクションになっていますね。コンストラクタインジェクションにしておきましょう。

2019-07-23 01:27 UTC, shunji-yamaguchi commented on src/main/java/jp/co/esm/bento/application/service/BentoService.java
> +            return order.get();
@reika-takamiya 
`{}` を省略されていますが、可読性を考えるとあまり良くないと思います。
省略せず書いておくのが良いと思います。

2019-07-23 01:27 UTC, shunji-yamaguchi commented on src/test/java/jp/co/esm/bento/application/controller/BentoControllerTest.java
> +                .andExpect(jsonPath("$[0].bento_id").value(bentoOrder.getBentoId()))
@reika-takamiya 
ゲッターのメソッド名が間違っていますね。修正しておいてください。
getRiceIdとgetArrivalDateも同様です。

2019-07-23 01:27 UTC, shunji-yamaguchi commented on src/test/java/jp/co/esm/bento/application/service/BentoServiceTest.java
> +                null, "hoge", 1, 0, LocalDate.now().toString()
@reika-takamiya 
`LocalDate.now()` は実行した時間で値が変わるので、このままだと後述の`() -> assertEquals("2019-07-22", after.get(0).getArrival_date())` でテストが失敗します。
修正しておいてください。

2019-07-23 01:27 UTC, shunji-yamaguchi commented on src/test/java/jp/co/esm/bento/application/service/BentoServiceTest.java
> +    ,"insert into bento_order values(2,'ドナルド',1,1,'2019-07-19');insert into bento_order values(3,'デイジー',2,0,'2019-07-27');"})
@reika-takamiya 
１タブ空けておきましょう。
また、insertを２クエリ書いてますが、１クエリずつに分けておいてほうが良いと思います。

2019-07-23 03:02 UTC, reika-takamiya commented on src/main/java/jp/co/esm/bento/application/controller/BentoController.java
> +//@NoArgsConstructor
@shunji-yamaguchi
不要なコメント削除しました。

2019-07-23 03:02 UTC, reika-takamiya commented on src/main/java/jp/co/esm/bento/application/controller/BentoController.java
>          return bentoService.selectAll();
@shunji-yamaguchi
RestControllerクラスを作成しました。

2019-07-23 03:03 UTC, reika-takamiya commented on src/main/java/jp/co/esm/bento/application/controller/BentoController.java
> +        return "order";
@shunji-yamaguchi
order.htmlを作成しました。

2019-07-23 03:03 UTC, reika-takamiya commented on src/main/java/jp/co/esm/bento/application/controller/BentoController.java
> +            return "orderHistory";
@shunji-yamaguchi
orderHistory.htmlを作成しました。

2019-07-23 03:03 UTC, reika-takamiya commented on src/main/java/jp/co/esm/bento/application/service/BentoService.java
> +    private BentoRepository bentoRepository;
@shunji-yamaguchi
コンストラクタインジェクションに修正しました。

2019-07-23 03:04 UTC, reika-takamiya commented on src/main/java/jp/co/esm/bento/application/service/BentoService.java
> +            return order.get();
@shunji-yamaguchi
{ }を追加しました。

2019-07-23 03:04 UTC, reika-takamiya commented on src/test/java/jp/co/esm/bento/application/service/BentoServiceTest.java
> +                null, "hoge", 1, 0, LocalDate.now().toString()
@shunji-yamaguchi
createメソッドのassertEqualsを修正しました。

2019-07-23 03:05 UTC, reika-takamiya commented on src/test/java/jp/co/esm/bento/application/service/BentoServiceTest.java
> +    ,"insert into bento_order values(2,'ドナルド',1,1,'2019-07-19');insert into bento_order values(3,'デイジー',2,0,'2019-07-27');"})
@shunji-yamaguchi
１クエリずつに修正しました。

2019-07-23 03:07 UTC, reika-takamiya commented
@shunji-yamaguchi 
@hironoriohashi
修正しました。

BentoControllerTestクラスは前回間違えたものをpushしてしまったので、BentoControllerTestクラスとBentoRestControllerTestクラスはまた違うPRであげ直します。
今回はBentoServiceTestクラスだけお願いします 🙏 

レビューよろしくお願いします！

2019-07-23 07:49 UTC, shunji-yamaguchi requested changes
@reika-takamiya 
レビューしました。ご確認よろしくお願いいたします。

2019-07-23 07:49 UTC, shunji-yamaguchi commented on src/main/resources/templates/orderHistory.html
> +<a href="/">Submit another message</a>
@reika-takamiya 
`/`へのリンクがありますが、現状定義されていないパスなのでクリックするとエラーになりますね。
正しいパスに修正するか、不要であれば削除しておいてください。

2019-07-23 07:49 UTC, shunji-yamaguchi commented on src/main/resources/templates/order.html
> +<h1>ユーザー登録</h1>
@reika-takamiya 
「ユーザー登録」となっていますが、弁当を注文するフォームのようなので違和感があります。
`<title>ユーザー登録</title>`についても同様です。

2019-07-23 07:49 UTC, shunji-yamaguchi commented on src/test/java/jp/co/esm/bento/application/service/BentoServiceTest.java
> +                () -> assertEquals(LocalDate.now().toString(), after.get(0).getArrival_date())
@reika-takamiya 
65行目と75行目の間に日付が変わるとエラーになりそうです（ほぼないでしょうが）。
`LocalDate.now()`で取得した日付を使うなら一度変数に代入しておいて、`new BentoOrder`と`assertEquals`で確実に同じ日付が使われるようにしておくと良いです

2019-07-24 04:47 UTC, reika-takamiya commented on src/main/resources/templates/orderHistory.html
> +<a href="/">Submit another message</a>
@shunji-yamaguchi
不要な文を削除しました。

2019-07-24 04:47 UTC, reika-takamiya commented on src/main/resources/templates/order.html
> +<h1>ユーザー登録</h1>
@shunji-yamaguchi
注文フォームに修正しました。

2019-07-24 04:48 UTC, reika-takamiya commented on src/test/java/jp/co/esm/bento/application/service/BentoServiceTest.java
> +                () -> assertEquals(LocalDate.now().toString(), after.get(0).getArrival_date())
@shunji-yamaguchi
変数に代入するよう修正しました。

2019-07-24 04:49 UTC, reika-takamiya commented
@shunji-yamaguchi 
@hironoriohashi
修正しました。レビューお願いします。

2019-07-24 04:50 UTC, shunji-yamaguchi approved these changes
@reika-takamiya 
良いと思います 🆗

2019-07-24 07:01 UTC, reika-takamiya commented
@shunji-yamaguchi 
@hironoriohashi
ありがとうございます！

次のタスクでマージしたものを使いたいのでマージします 🙏

2019-07-24 07:01 UTC, merged