全員が注文履歴を見ることができる
kenta-yamazaki/Bento pull request #12
Opened 2019-07-22 04:57 UTC by reika-takamiya

#10　
 `http://localhost:8080/bento/user/orderList`をGetリクエストすると、過去に注文した全ての履歴を見ることができるようにしました。(注文者名、弁当の種類、ご飯の有無、到着日)
レビューお願いします。

2019-07-23 08:50 UTC, shunji-yamaguchi requested changes
@reika-takamiya 
レビューしました。ご確認をよろしくお願いします。

#11 での`build.gradle`の修正を適応しないと動かないコードになっていますね。
また #11 では`schema.sql` に修正が入ったので、マージすると予想外のエラーが起きるなどありえそうです。（本プルリクのコードについては大丈夫そうに見えます）
こういった共通部分の修正は、先にプルリクを出してマージしたり、コミットを別に作ってcherry-pickするなどしておくと良いと思います。

2019-07-23 08:50 UTC, shunji-yamaguchi commented on src/main/java/jp/co/esm/bento/application/controller/BentoController.java
> +    public String create(@Validated @ModelAttribute BentoOrder bentoOrder, BindingResult result, Model model) {
@reika-takamiya 
これはこのプルリクには関係ないコードですね、削除しておきましょう。

2019-07-23 08:50 UTC, shunji-yamaguchi commented on src/main/java/jp/co/esm/bento/application/controller/BentoController.java
> +    public String displayAdd(Model model) {
@reika-takamiya 
これはこのプルリクには関係ないコードですね、削除しておきましょう。

2019-07-25 01:03 UTC, reika-takamiya commented on src/main/java/jp/co/esm/bento/application/controller/BentoController.java
> +    public String create(@Validated @ModelAttribute BentoOrder bentoOrder, BindingResult result, Model model) {
@shunji-yamaguchi
修正しました。

2019-07-25 01:03 UTC, reika-takamiya commented on src/main/java/jp/co/esm/bento/application/controller/BentoController.java
> +    public String displayAdd(Model model) {
@shunji-yamaguchi
修正しました。

2019-07-25 01:06 UTC, reika-takamiya commented
修正しました。
他にご指摘なければマージします。

2019-07-25 01:21 UTC, shunji-yamaguchi approved these changes
@reika-takamiya 
良いと思います 🆗

2019-07-25 01:32 UTC, shunji-yamaguchi commented
@reika-takamiya 
すいません。
 #11 で指摘すべきだったのですが、失敗するテストをマージしてしまうのはよくありません。
`BentoControllerTest`のゲッターの修正と`@Disabled`の付与をしておきましょう 🙏

2019-07-25 01:52 UTC, reika-takamiya commented
@shunji-yamaguchi 
@hironoriohashi
修正しました。
他にご指摘なければマージします。

2019-07-25 01:55 UTC, shunji-yamaguchi approved these changes
@reika-takamiya 
良いと思います 🆗

2019-07-25 01:56 UTC, merged