注文者がメニュー選べる
kenta-yamazaki/Bento pull request #13
Opened 2019-07-25 05:26 UTC by reika-takamiya

@shunji-yamaguchi
@hironoriohashi
 #7 作成しました。
レビューお願いします。

2019-07-25 05:41 UTC, hironoriohashi commented
コンフリクトを起こしています。
`BentoController.java`を修正してコンフリクトを解消してみてください。

2019-07-25 06:11 UTC, reika-takamiya commented
@hironoriohashi 
コンフリクト解消しました。

2019-07-25 10:10 UTC, shunji-yamaguchi requested changes
@reika-takamiya 
レビューしました、ご確認をよろしくお願いします。

2019-07-25 10:10 UTC, shunji-yamaguchi commented on src/main/java/jp/co/esm/bento/application/controller/BentoController.java
> +            model.addAttribute("bentoName", bentoRepository.findById(bentoOrder.getBento_id()).get().getName());
@reika-takamiya 
コントローラーから直接リポジトリを呼び出すのは良くないです。サービスを介するよう修正しておいてください。

2019-07-25 10:10 UTC, shunji-yamaguchi commented on src/main/java/jp/co/esm/bento/application/controller/BentoController.java
> +        selectMap.put("2", "元気");
@reika-takamiya 
`bento`テーブルから取得したデータを使用すれば、テーブルのデータが変更になってもコードの修正が不要になります。
修正してみてください。

2019-07-25 10:10 UTC, shunji-yamaguchi commented on src/main/java/jp/co/esm/bento/application/entity/BentoOrder.java
> +    }
@reika-takamiya 
Lombokを使用しているので、コンストラクタはLombokで作るようにするのが良いです。

2019-07-25 10:10 UTC, shunji-yamaguchi commented on src/main/java/jp/co/esm/bento/application/entity/Rice.java
> +public class Rice {
@reika-takamiya 
このブランチには必要ないエンティティだと思います。
削除しておきましょう。

2019-07-25 10:10 UTC, shunji-yamaguchi commented on src/main/resources/templates/order.html
> +            </div>
@reika-takamiya 
ラジオボタンがテーブルの要素としてみなされずレイアウトがずれてますね。
他の要素と同じように、「弁当の種類」の横に表示されるよう修正してください。

2019-07-25 10:10 UTC, shunji-yamaguchi commented on src/main/resources/templates/order.html
>              <th class="cell_required"></th>
@reika-takamiya 
`<th class="cell_required"></th>`は使用していないように見えますがどうですか？不要であれば削除しておいてください。

2019-07-25 10:10 UTC, shunji-yamaguchi commented on src/test/java/jp/co/esm/bento/application/service/BentoServiceTest.java
> +               1 , "hoge", 1, 0, now.toString()
@reika-takamiya 
nullを渡せなくなったのは`bentoOrderRepository`のコンストラクタを変更したのが原因です。
`bentoService.create`で挿入するデータのidは自動採番されるのが正しいので、nullを渡すようにしましょう。

2019-07-26 02:52 UTC, reika-takamiya commented on src/main/java/jp/co/esm/bento/application/controller/BentoController.java
> +            model.addAttribute("bentoName", bentoRepository.findById(bentoOrder.getBento_id()).get().getName());
@shunji-yamaguchi
サービスクラスを介するように修正しました。

2019-07-26 02:53 UTC, reika-takamiya commented on src/main/java/jp/co/esm/bento/application/entity/BentoOrder.java
> +    }
@shunji-yamaguchi
コンストラクタを削除しました。

2019-07-26 02:54 UTC, reika-takamiya commented on src/main/java/jp/co/esm/bento/application/entity/Rice.java
> +public class Rice {
@shunji-yamaguchi
不要なエンティティクラスを削除しました。

2019-07-26 02:54 UTC, reika-takamiya commented on src/main/resources/templates/order.html
> +            </div>
@shunji-yamaguchi
レイアウトを修正しました。

2019-07-26 02:54 UTC, reika-takamiya commented on src/main/resources/templates/order.html
>              <th class="cell_required"></th>
@shunji-yamaguchi
`<th class="cell_required"></th>`を削除しました。

2019-07-26 02:55 UTC, reika-takamiya commented on src/test/java/jp/co/esm/bento/application/service/BentoServiceTest.java
> +               1 , "hoge", 1, 0, now.toString()
@shunji-yamaguchi
自動採番されるように修正しました。

2019-07-26 02:55 UTC, reika-takamiya commented
@shunji-yamaguchi 
@hironoriohashi 
修正しました。
サイドレビューお願いします！

2019-07-26 04:28 UTC, shunji-yamaguchi approved these changes
@reika-takamiya 
良いと思います 🆗

2019-07-26 04:32 UTC, hironoriohashi approved these changes
良いと思います

2019-07-26 04:34 UTC, reika-takamiya commented
@shunji-yamaguchi 
@hironoriohashi 
ありがとうございます！
マージします！

2019-07-26 04:34 UTC, merged