注文する人がご飯の有無を選べる
kenta-yamazaki/Bento pull request #14
Opened 2019-07-25 06:13 UTC by reika-takamiya

@shunji-yamaguchi
@hironoriohashi

#8 を作成しました。
レビューお願いします。

2019-07-25 10:24 UTC, shunji-yamaguchi requested changes
@reika-takamiya 
レビューしました。ご確認をよろしくお願いします。

2019-07-25 10:24 UTC, shunji-yamaguchi commented on src/main/java/jp/co/esm/bento/application/controller/BentoController.java
> +            model.addAttribute("riceAvailablity", riceRepository.findById(bentoOrder.getBento_id()).get().getAvailability());
@reika-takamiya
コントローラーから直接リポジトリを呼び出すのは良くないです。サービスを介するよう修正しておいてください。
また、取得するidが`Bento_id`になってます。

2019-07-25 10:24 UTC, shunji-yamaguchi commented on src/main/java/jp/co/esm/bento/application/controller/BentoController.java
> +        selectMap.put("1", "ご飯なし");
@reika-takamiya 
テーブルから取得したデータを使用すれば、テーブルのデータが変更になってもコードの修正が不要になります。
修正してみてください。

2019-07-25 10:24 UTC, shunji-yamaguchi commented on src/main/resources/templates/order.html
> +            <input type="radio" name="rice_id" th:value="${rice.key}" th:text="${rice.value}" th:field="*{rice_id}" />
@reika-takamiya 
ラジオボタンがテーブルの要素としてみなされずレイアウトがずれてますね。
他の要素と同じように、「ご飯の有無」の横に表示されるよう修正してください。

2019-07-26 04:32 UTC, reika-takamiya commented on src/main/java/jp/co/esm/bento/application/controller/BentoController.java
> +            model.addAttribute("riceAvailablity", riceRepository.findById(bentoOrder.getBento_id()).get().getAvailability());
@shunji-yamaguchi
サービスを介するように修正しました。

2019-07-26 04:33 UTC, reika-takamiya commented on src/main/resources/templates/order.html
> +            <input type="radio" name="rice_id" th:value="${rice.key}" th:text="${rice.value}" th:field="*{rice_id}" />
@shunji-yamaguchi
レイアウトを修正しました。

2019-07-26 04:33 UTC, reika-takamiya commented
@shunji-yamaguchi 
@hironoriohashi
修正しました。
再度レビューお願いします！

2019-07-26 05:29 UTC, shunji-yamaguchi approved these changes
@reika-takamiya 
良いと思います 🆗

2019-07-26 05:41 UTC, hironoriohashi approved these changes
良いと思います。

2019-07-26 06:20 UTC, reika-takamiya commented
@shunji-yamaguchi 
@hironoriohashi 
ありがとうございます。
マージします。

2019-07-26 06:29 UTC, merged