RestControllerクラスのテストを作成
kenta-yamazaki/Bento pull request #21
Opened 2019-07-30 01:18 UTC by reika-takamiya

@shunji-yamaguchi
@hironoriohashi
#20 を作成しました。
レビューよろしくお願い致します。

2019-07-30 04:36 UTC, shunji-yamaguchi requested changes
@reika-takamiya 
レビューしました。ご確認をよろしくお願いします。

2019-07-30 04:36 UTC, shunji-yamaguchi commented on src/test/java/jp/co/esm/bento/application/controller/BentoRestControllerTest.java
> +        bentoOrderList.add(bentoOrder1);
@reika-takamiya 
`bentoOrderList` `bentoOrder` `bentoOrder1` を生成していますが、テストで必要なのは`bentoOrder1`のみですね。
不要なものは削除しておいてください。

2019-07-30 07:31 UTC, reika-takamiya commented on src/test/java/jp/co/esm/bento/application/controller/BentoRestControllerTest.java
> +        bentoOrderList.add(bentoOrder1);
@shunji-yamaguchi
不要な文を削除しました。

2019-07-30 07:31 UTC, reika-takamiya commented
@shunji-yamaguchi 
@hironoriohashi
修正しました。
再度レビューお願いします。

2019-07-30 07:37 UTC, shunji-yamaguchi approved these changes
@reika-takamiya 
良いと思います 🆗

2019-07-30 08:47 UTC, hironoriohashi approved these changes
良いと思います。

2019-07-31 00:24 UTC, reika-takamiya commented
@shunji-yamaguchi 
@hironoriohashi 
ありがとうございます！
マージします。

2019-07-31 00:24 UTC, merged