DB接続
kenta-yamazaki/Bento pull request #5
Opened 2019-06-28 09:05 UTC by kenta-yamazaki

@shunji-yamaguchi
@hironoriohashi
途中ですが、DB接続まで行ったのでPR出します。
レビューお願いします！

2019-07-01 08:56 UTC, shunji-yamaguchi requested changes
@kenta-yamazaki 
レビューしました。よくわからないコメントがあれば質問してください 🙇

2019-07-01 08:56 UTC, shunji-yamaguchi commented on src/main/java/com/Bento/Bento/application/controller/BentoController.java
>      BentoRepository repository;
@kenta-yamazaki 
スコープは最小にすべきなので、privateにしておきましょう。
インジェクションは必要なクラスごとに行うので、`private`か`protected`になるのが自然だと思います。

またフィールドインジェクションを使用していますが、コンストラクタインジェクションのほうが推奨されるそうです。
参考：http://pppurple.hatenablog.com/entry/2016/12/29/233141
フィールドインジェクションでも問題はないですが、余裕があれば修正するのが良いと思います。

2019-07-01 08:56 UTC, shunji-yamaguchi commented on src/main/java/com/Bento/Bento/application/controller/BentoController.java
> +        @RequestMapping("/all")
@kenta-yamazaki 
インデントがずれてますね。修正しておいてください。

2019-07-01 08:56 UTC, shunji-yamaguchi commented on src/main/java/com/Bento/Bento/application/controller/BentoController.java
> +        @RequestMapping("/select")
@kenta-yamazaki 
インデントがずれてますね。修正しておいてください。

2019-07-01 08:56 UTC, shunji-yamaguchi commented on src/main/java/com/Bento/Bento/application/controller/BentoController.java
> +//    }
@kenta-yamazaki 
不要なコードであれば削除しておいてください。

2019-07-01 08:56 UTC, shunji-yamaguchi commented on src/main/java/com/Bento/Bento/application/controller/BentoController.java
> +        Counter result = list.get();
@kenta-yamazaki 
30行目で`list.get()`を実行してそのまま返しているので、不要そうです。

2019-07-01 08:56 UTC, shunji-yamaguchi commented on src/main/java/com/Bento/Bento/application/counter/Counter.java
> +    }
@kenta-yamazaki 
このクラスは`@Data`が指定されているので、ゲッターはLombokが作成してくれます。
なのでゲッターを書く必要はありません。

2019-07-01 08:56 UTC, shunji-yamaguchi commented on src/main/java/com/Bento/Bento/application/repository/BentoRepository.java
> +    //List<Counter> findById(String id);
@kenta-yamazaki
不要なコードであれば削除しておいてください。

2019-07-01 08:56 UTC, shunji-yamaguchi commented on src/main/java/com/Bento/Bento/application/counter/Counter.java
>  public class Counter {
@kenta-yamazaki 
このクラスは`test_table`テーブルの値を保持するためのEntityですね。
Entityはテーブルと同じ名前にしておくのが分かりやすくて良いです。
この場合はjavaなのでキャメルケースに直して`TestTable`とすると良いと思います。

2019-07-01 08:56 UTC, shunji-yamaguchi commented on src/main/java/com/Bento/Bento/application/counter/Counter.java
> +import javax.persistence.*;
@kenta-yamazaki 
staticインポートになっていますね。
直しておいてください。

2019-07-01 08:56 UTC, shunji-yamaguchi commented on src/main/java/com/Bento/Bento/application/counter/Counter.java
>  package com.Bento.Bento.application.counter;
@kenta-yamazaki 
パッケージ名が`counter`となっていますが、おそらくこのパッケージは`Entity`クラスをまとめておくパッケージになりますよね？
なのでパッケージ名も`entity`としておくのが良いと思います。

2019-07-01 08:56 UTC, shunji-yamaguchi commented on src/main/java/com/Bento/Bento/application/controller/BentoController.java
> +        Optional<Counter> list = repository.findById(id);
@kenta-yamazaki 
コントローラークラスからリポジトリクラスを呼び出していますが、リポジトリを介してデータ操作を行うのはサービスクラスの役目です。
なのでサービスクラスを作成し、コントローラはサービスを呼び出して結果を受け取りレスポンスを返す、サービスはコントローラからリクエストを受け取ってリポジトリを呼び出し結果をコントローラに返す、とするのが良いです。

参考：https://qiita.com/cross-xross/items/144f8bde2ef6fa4b379f#1-controllerservicerepository%E3%81%AB%E5%88%86%E5%89%B2%E3%81%97%E3%81%A6%E3%81%84%E3%82%8B%E3%81%8B

2019-07-01 08:56 UTC, shunji-yamaguchi commented on src/main/java/com/Bento/Bento/application/counter/Counter.java
>      private String id;
@kenta-yamazaki 
idがプライマリキーであれば、テーブルのカラムは数値型になっていませんか？
数値型であればStringでなく、テーブルのカラムとあった型を指定すべきです。

2019-07-01 08:56 UTC, shunji-yamaguchi commented on src/main/java/com/Bento/Bento/application/repository/BentoRepository.java
>      List<Counter> findByIdNotIn(ArrayList<String> ids);
@kenta-yamazaki 
このクラスのメソッドは、呼び出していたコントローラのコードがコメントアウトされたので、どこからも呼ばれていませんね。
不要であれば削除しておいてください。

2019-07-01 09:00 UTC, shunji-yamaguchi commented on src/main/java/com/Bento/Bento/application/controller/BentoController.java
>      BentoRepository repository;
> コンストラクタで

やはりコンストラクタインジェクションを使用すべきようなので、コンストラクタインジェクションに修正しておいてください 🙏

2019-07-03 06:50 UTC, kenta-yamazaki commented on src/main/java/com/Bento/Bento/application/controller/BentoController.java
>      BentoRepository repository;
@shunji-yamaguchi
コンストラクタインジェクションに修正しました。

2019-07-03 06:51 UTC, kenta-yamazaki commented on src/main/java/com/Bento/Bento/application/controller/BentoController.java
> +        @RequestMapping("/all")
@shunji-yamaguchi
インデントを修正しました。

2019-07-03 06:51 UTC, kenta-yamazaki commented on src/main/java/com/Bento/Bento/application/controller/BentoController.java
> +        @RequestMapping("/select")
@shunji-yamaguchi
インデントを修正しました。

2019-07-03 06:51 UTC, kenta-yamazaki commented on src/main/java/com/Bento/Bento/application/controller/BentoController.java
> +//    }
@shunji-yamaguchi
不要なコードを削除しました。

2019-07-03 06:52 UTC, kenta-yamazaki commented on src/main/java/com/Bento/Bento/application/controller/BentoController.java
> +        Counter result = list.get();
@shunji-yamaguchi
コードの修正をしました。

2019-07-03 06:52 UTC, kenta-yamazaki commented on src/main/java/com/Bento/Bento/application/counter/Counter.java
> +    }
@shunji-yamaguchi
lombokを使用しゲッターを削除しました。

2019-07-03 06:53 UTC, kenta-yamazaki commented on src/main/java/com/Bento/Bento/application/repository/BentoRepository.java
> +    //List<Counter> findById(String id);
@shunji-yamaguchi
不要なコードを削除しました。

2019-07-03 06:53 UTC, kenta-yamazaki commented on src/main/java/com/Bento/Bento/application/counter/Counter.java
>  public class Counter {
@shunji-yamaguchi
キャメルケースに修正しました。

2019-07-03 06:53 UTC, kenta-yamazaki commented on src/main/java/com/Bento/Bento/application/counter/Counter.java
> +import javax.persistence.*;
import文を修正しました。

2019-07-03 06:54 UTC, kenta-yamazaki commented on src/main/java/com/Bento/Bento/application/counter/Counter.java
>  package com.Bento.Bento.application.counter;
@shunji-yamaguchi
パッケージを変更しました。

2019-07-03 06:55 UTC, kenta-yamazaki commented on src/main/java/com/Bento/Bento/application/controller/BentoController.java
> +        Optional<Counter> list = repository.findById(id);
@shunji-yamaguchi
サービスクラスを作成し、修正しました。

2019-07-03 06:55 UTC, kenta-yamazaki commented on src/main/java/com/Bento/Bento/application/counter/Counter.java
>      private String id;
@shunji-yamaguchi
idをint型に修正しました。

2019-07-03 06:55 UTC, kenta-yamazaki commented on src/main/java/com/Bento/Bento/application/repository/BentoRepository.java
>      List<Counter> findByIdNotIn(ArrayList<String> ids);
@shunji-yamaguchi
不要なコードを削除しました。

2019-07-03 06:56 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi
修正しました。
レビューお願いいたします！

2019-07-03 07:38 UTC, hironoriohashi commented
`Bento/src/main/java/com/Bento/Bento/application/`フォルダとは別に
`Bento/src/main/java/com/Bento/application/`フォルダが追加さていますが、どちらも必要でしょうか？

2019-07-03 07:45 UTC, kenta-yamazaki commented
後者の`Bento/src/main/java/com/Bento/application/`だけが必要です。
削除しておきます。:bow:

2019-07-04 01:06 UTC, shunji-yamaguchi requested changes
@kenta-yamazaki 
レビューしました。ご確認をよろしくお願いします。

2019-07-04 01:06 UTC, shunji-yamaguchi commented on src/main/java/com/Bento/application/controller/BentoController.java
> +import java.util.Optional;
@kenta-yamazaki 
不要なimportですね、削除しておいてください。

2019-07-04 01:06 UTC, shunji-yamaguchi commented on src/main/java/com/Bento/application/controller/BentoController.java
> +        List<Counter> list = bentoRepository.findAll();
@kenta-yamazaki 
この処理についてもサービスクラスをを呼び出して行うよう修正してみてください。

2019-07-04 01:06 UTC, shunji-yamaguchi commented on src/main/java/com/Bento/application/controller/BentoController.java
> +    private BentoService bentoService;
@kenta-yamazaki 
コンストラクタインジェクションにしたので、フィールドごとの`@Autowired`は不要だと思います。

また、コンストラクタインジェクションの利点にインジェクションするフィールド変数をfinalできる、があるのでfinalにしておくと良いと思います。
そうするとコンストラクタインジェクション用にコンストラクタを作成するLombokアノテーションを、`@AllArgsConstructor`でなく`@RequiredArgsConstructor`にもできそうです。

これらは`BentoService`クラスにも同じことがいえるので、`BentoService`についても同様にお願いします。

（このコメントを書くのに参考にしたページ：https://qiita.com/old-stone/items/35cc7fb767b0cde7f059 ）

2019-07-04 01:06 UTC, shunji-yamaguchi commented on src/main/java/com/Bento/application/service/BentoService.java
> +@NoArgsConstructor
@kenta-yamazaki 
引数なしコンストラクタは使用していないはずなので不要だと思います。削除しておいてください。

2019-07-04 01:06 UTC, shunji-yamaguchi commented on src/main/java/com/Bento/application/BentoApplication.java
> +package com.Bento.application;
@kenta-yamazaki 
idobataのコメントであったとおり、パッケージ名の修正もお願いします。

2019-07-04 01:06 UTC, shunji-yamaguchi commented on src/main/java/com/Bento/application/entity/Counter.java
> +public class Counter {
@kenta-yamazaki 
すいません。私がコメントで言いたかったのは、`Entity`クラスの名前は対応するテーブルの名前と同じにすると、分かりやすくて良いということです。
なのでテーブル名が`test_table`であれば、その値を保持するための`Entity`クラスの名前は`TestTable`が良いと思う、ということです。

あと今更ですが、テーブル名に`table`とつけるのは冗長なので、`test`とするのが良いと思います。

2019-07-04 04:17 UTC, kenta-yamazaki commented on src/main/java/com/Bento/application/entity/Counter.java
> +public class Counter {
@shunji-yamaguchi
テーブル名を`test`とした場合、クラス名を`Counter`ではなく`Test`にした方がいいという
解釈であっていますか？

2019-07-04 04:25 UTC, shunji-yamaguchi commented on src/main/java/com/Bento/application/entity/Counter.java
> +public class Counter {
@kenta-yamazaki 
はい、それが言いたいことです 🙇

2019-07-04 04:49 UTC, kenta-yamazaki commented on src/main/java/com/Bento/application/controller/BentoController.java
> +import java.util.Optional;
@shunji-yamaguchi
修正しました。

2019-07-04 04:50 UTC, kenta-yamazaki commented on src/main/java/com/Bento/application/controller/BentoController.java
> +        List<Counter> list = bentoRepository.findAll();
@shunji-yamaguchi
修正しました。

2019-07-04 04:51 UTC, kenta-yamazaki commented on src/main/java/com/Bento/application/controller/BentoController.java
> +    private BentoService bentoService;
@shunji-yamaguchi
解説していただきありがとうございます！
修正しました。

2019-07-04 04:51 UTC, kenta-yamazaki commented on src/main/java/com/Bento/application/service/BentoService.java
> +@NoArgsConstructor
@shunji-yamaguchi
不要な文を削除しました。

2019-07-04 04:51 UTC, kenta-yamazaki commented on src/main/java/com/Bento/application/BentoApplication.java
> +package com.Bento.application;
@shunji-yamaguchi
修正しました。

2019-07-04 04:52 UTC, kenta-yamazaki commented on src/main/java/com/Bento/application/entity/Counter.java
> +public class Counter {
@shunji-yamaguchi
ありがとうございます！
修正しました。

2019-07-04 04:53 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi 
修正いたしました。
レビューお願いします。

2019-07-04 05:41 UTC, shunji-yamaguchi approved these changes
@kenta-yamazaki 
良いと思います 🆗

2019-07-04 05:49 UTC, hironoriohashi commented on src/main/java/jp/co/esm/bento/application/service/BentoService.java
> +        return list.get();
一意な値であるidで検索したデータを格納する変数名が`list`であるのは違和感があります。
また、`Optional`クラスの`get`メソッドは`NoSuchElementException`をスローする場合があるため、メソッドに明示した方が良いと思います。

2019-07-08 04:29 UTC, kenta-yamazaki commented on src/main/java/jp/co/esm/bento/application/service/BentoService.java
> +        return list.get();
@hironoriohashi
修正いたしました。

2019-07-08 04:32 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi 
かんばんの`DBを設計する`までこのPRで行ない、この後から別のブランチ切って進めていこうと思っています。
修正、追加いたしました。レビューお願いいたします。

2019-07-09 00:00 UTC, hironoriohashi commented on src/main/java/jp/co/esm/bento/application/service/BentoService.java
> +        return list.get();
変数名がまだ直っていないように見えます。
`NoSuchElementException`のスローはOKです。

2019-07-09 01:12 UTC, shunji-yamaguchi requested changes
@kenta-yamazaki 
レビューしました。ご確認をよろしくお願いします。

2019-07-09 01:12 UTC, shunji-yamaguchi commented on src/main/resources/schema.sql
> +    order_menu int NOT NULL,
@kenta-yamazaki 
`order_menu` カラムには、`bento_info` テーブルのプライマリキーが入るんですかね？
そうであれば、カラム名はそれが分かるような名前がいいかなと思いました。
（対応するプライマリキーと同名にする、対象テーブル名 + id とする など）
`order_rice` についても同様です。

2019-07-09 01:12 UTC, shunji-yamaguchi commented on src/main/resources/schema.sql
> +    order_id SERIAL NOT NULL,
@kenta-yamazaki 
プライマリキーの名前は、`id` または `テーブル名 + id` とするほうが、分かりやすくて良いかなと思いました。
`bento_info` と `rice_info` テーブルについても同様です。

2019-07-09 01:12 UTC, shunji-yamaguchi commented on src/main/resources/schema.sql
> +CREATE TABLE if not exists bento_info(
@kenta-yamazaki 
`info` は特に意味のない名前なので、必要な理由がなければテーブル名は `bento` とするのが良いと思います。
`rice_info` テーブルについても同様です。

2019-07-09 01:12 UTC, shunji-yamaguchi commented on src/main/resources/schema.sql
> +    bento_price int NOT NULL,
@kenta-yamazaki 
テーブル名が `bento_info` なので、`bento_price` という名前は冗長かなと思いました。
単純に `price` としても良いと思います。
`rice_price` についても同様です。

2019-07-09 05:25 UTC, kenta-yamazaki commented on src/main/java/jp/co/esm/bento/application/service/BentoService.java
> +        return list.get();
@hironoriohashi
`OrdererData`という変数名でもよろしいでしょうか？

2019-07-09 05:43 UTC, hironoriohashi commented on src/main/java/jp/co/esm/bento/application/service/BentoService.java
> +        return list.get();
`ordererData`の`Data`が冗長に感じます。
`orderer`で良いと思います。

また、取得する内容が注文者の情報ではなく、注文の内容に感じるため
`orderer`よりも`order`の方が良いかもしれません。

2019-07-09 06:44 UTC, kenta-yamazaki commented on src/main/resources/schema.sql
> +    order_menu int NOT NULL,
@shunji-yamaguchi
修正しました。

2019-07-09 06:44 UTC, kenta-yamazaki commented on src/main/resources/schema.sql
> +    order_id SERIAL NOT NULL,
@shunji-yamaguchi
修正しました。

2019-07-09 06:45 UTC, kenta-yamazaki commented on src/main/resources/schema.sql
> +CREATE TABLE if not exists bento_info(
@shunji-yamaguchi
修正しました。

2019-07-09 06:45 UTC, kenta-yamazaki commented on src/main/resources/schema.sql
> +    bento_price int NOT NULL,
@shunji-yamaguchi
修正しました。

2019-07-09 06:46 UTC, kenta-yamazaki commented on src/main/java/jp/co/esm/bento/application/service/BentoService.java
> +        return list.get();
@hironoriohashi
ありがとうございます。orderに修正しました。

2019-07-09 06:47 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi 
修正しました。レビューお願いいたします。

2019-07-09 06:52 UTC, hironoriohashi approved these changes
良いと思います

2019-07-09 07:24 UTC, shunji-yamaguchi requested changes
@kenta-yamazaki 
１点追加しました、ご確認をよろしくお願いします。

2019-07-09 07:24 UTC, shunji-yamaguchi commented on src/main/resources/schema.sql
> +    arrival date NOT NULL,
@kenta-yamazaki 
日付であることが分かるように`arrival_date`とすると良いと思います。

2019-07-10 02:40 UTC, kenta-yamazaki commented on src/main/resources/schema.sql
> +    arrival date NOT NULL,
@shunji-yamaguchi
修正いたしました。

2019-07-10 02:41 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi 
修正しました。再度レビューお願いします。

2019-07-10 02:43 UTC, shunji-yamaguchi approved these changes
@kenta-yamazaki 良いと思います 🆗

2019-07-10 02:44 UTC, hironoriohashi approved these changes
良いと思います。

2019-07-10 02:57 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi 
ありがとうございます。マージします。

2019-07-10 02:58 UTC, merged